### ISSUE TITLE
Undefined function or variable 'NonlinearFactorGraph'

### ISSUE THREAD

**Issue by zssjh** [dongjing3309/gtsam-examples#1]
I try to run the package and meet this problem:
Undefined function or variable 'NonlinearFactorGraph'.
Error in Pose2SLAMExample (line 22)
graph = NonlinearFactorGraph;
What should I do next?
thanks!

**Comment by dongjing3309** [comment]
Do you means the Matlab example? Check you have added the GTSAM toolbox install path in your Matlab path

**Comment by zssjh** [comment]
Yes, and I have already added the GTSAM toolbox install path in my Matlab path. My toolbox contents:
.
├── +gtsamexamples
│   └── GPSPose2Factor.m
└── gtsamexamples_wrapper.mexa64
Is there any problem?

**Comment by dongjing3309** [comment]
That's all the contents? You also need install GTSAM's toolbox in the same path, not only the example's toolbox. You should also see +gtsam/ and gtsam_wrapper.mexa64

**Comment by dongjing3309** [comment]
Close due to no following ups. If anyone see this issue again, feel free to re-open

**Comment by Junkai-Liu** [comment]
@dongjing3309 the same problem is occuring to me,I can't see how to fix that,Do you mean add the gtsam/matlab to matlab searching path?
