### ISSUE TITLE
/usr/bin/ld: cannot find -lBoost::serialization

### ISSUE THREAD

**Issue by zephyr06** [dongjing3309/gtsam-examples#5]
This error is a little weird.. When I first run the total program, it works well. But then it breaks and reports error when using make (I already downloaded a new version):

Scanning dependencies of target gtsamexamples
[  8%] Building CXX object cpp/CMakeFiles/gtsamexamples.dir/functions.cpp.o
[ 16%] Linking CXX shared library libgtsamexamples.so
/usr/bin/ld: cannot find -lBoost::serialization
/usr/bin/ld: cannot find -lBoost::system
/usr/bin/ld: cannot find -lBoost::filesystem
/usr/bin/ld: cannot find -lBoost::thread
/usr/bin/ld: cannot find -lBoost::date_time
/usr/bin/ld: cannot find -lBoost::regex
/usr/bin/ld: cannot find -lBoost::timer
/usr/bin/ld: cannot find -lBoost::chrono
collect2: error: ld returned 1 exit status
cpp/CMakeFiles/gtsamexamples.dir/build.make:85: recipe for target 'cpp/libgtsamexamples.so' failed
make[2]: *** [cpp/libgtsamexamples.so] Error 1
CMakeFiles/Makefile2:582: recipe for target 'cpp/CMakeFiles/gtsamexamples.dir/all' failed
make[1]: *** [cpp/CMakeFiles/gtsamexamples.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

But my Boost.Python can run some tests alone. So are there any suggestions? Thanks a lot!

**Comment by zephyr06** [comment]
There are some warnings when using 'cmake ..'. The main part is repeated like follows:

CMake Warning (dev) at cpp/CMakeLists.txt:17 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "gtsamexamples" links to target "Boost::chrono" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by vigorbird** [comment]
Hello, I also meet the same question but I find the solution to solve it. In cmakelists.txt, you should write like this:
find_package(Boost REQUIRED COMPONENTS filesystem serialization system thread date_time regex timer chrono)

**Comment by dongjing3309** [comment]
Hi @Zephyr06 , do you see the same issue when compile and install GTSAM?

**Comment by vigorbird** [comment]
When I write gtsam code, I meet the same question you mentioned. I solve this problem like I said in github.




| |
yy
邮箱：fengyyml@163.com
|

Signature is customized by Netease Mail Master

On 03/28/2019 13:32, Jing Dong wrote:

Hi @Zephyr06 , do you see the same issue when compile and install GTSAM?

**Comment by zephyr06** [comment]
There is no problem when installing the standard GTSAM. So I finally found the same solution as above in the CMakeLists of GTSAM, and it works well.

**Comment by vigorbird** [comment]
This is my cmakelists.txt file.  Is it the same with you?
| |
yy

|
|
fengyyml@163.com
|
签名由网易邮箱大师定制
On 3/29/2019 06:28，Zephyr06<notifications@github.com> wrote：

There is no problem when installing the standard GTSAM. So I finally found the same solution as above in the CMakeLists of GTSAM, and it works well.
